name: CICD

on:
  push:
    branches:
      - 'gha'

jobs:
  build:
    name: CICD
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: us-west-2
    steps:
    - name: Checkout scm
      uses: actions/checkout@v3
    - name: Login to the DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Image tag
      id: set-tag
      run: echo "tag=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build
      env:
        COMMIT_SHA: ${{ steps.set-tag.outputs.tag }}
      run: |
        ./scripts/ci_build.sh
